version: '3'

services:
  forum:
    platform: "linux/amd64"
    image: .
    restart: "always"
    links:
      - postgis
    ports:
      - "4567:4567"
  postgis:
    platform: linux/amd64
    image: postgis/postgis:16-3.4-alpine
    restart: 'always'
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
