version: '3'

services:
    api:
        platform: linux/amd64
        image: discourse/base:2.0.20240123-0023
        restart: always
        links:
            - postgis
        ports:
            - "5000:5000"
        environment:
            - POSTGRES=postgres://docker:docker@postgis:5432/gis
    postgis:
        platform: linux/amd64
        image: postgis/postgis:16-3.4-alpine
        restart: 'always'
        ports:
            - 5433:5432
        environment:
            - POSTGRES_DB=gis
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=docker
